### ISSUE TITLE
Add Arcade Archives: Lightning Fighters

### ISSUE THREAD

**Issue by silverhook** [Alshie/does-it-flip#11]
[Apparently](https://twitter.com/NShmups/status/1321175842786054145) the following game is also FlipGrip compatible, but I don’t own it to test it out.

[Arcade Archives: Lightning Fighters](https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/Arcade-Archives-LIGHTNING-FIGHTERS-1829873.html)

**Comment by riccyjay** [comment]
Hey guys, I can confirm it is playable with a FlipGrip - same way as other ACA releases.

There's another ACA game, Image Fight, you could add.

Ghost Blade HD from Hucast and Eastasiasoft also supports FlipGrip.

And, last one, Missile Dancer, from Terrarin Games does too.

If you want any further info on these releases, feel free to hit me up on Twitter (@NShmups).

Cheers for doing this, by the way. It's a really great resource!

**Comment by silverhook** [comment]
Thanks for the list, @riccyjay (and thanks for doing the awesome video series on YT!).

Short instructions or any additional orientation-relevant notes on all the games that we sadly don’t own ourselves, would be greatly appreciated :+1:

**Comment by silverhook** [comment]
I’ve created separate tickets for the other games. If no-one beats me to it, will create PRs later this week for them.

**Comment by silverhook** [comment]
Closed through #14

**Comment by Alshie** [comment]
Thank you for these!
