### ISSUE TITLE
Add also developer field?

### ISSUE THREAD

**Issue by silverhook** [Alshie/does-it-flip#22]
Currently we only have the Publisher field, and while finding the developer on the eShop is not as easy, it might make sense for use to add that field.

What do you think?

**Comment by Alshie** [comment]
Yes, definitely. I'll start adding some today.

I don't think they list on the eShop very often but Wikipedia page usually fairly accurate.

**Comment by silverhook** [comment]
Die 28. 10. 20 et hora 11:38 Alan Wallace scripsit:
> I don't think they list on the eShop very often but Wikipedia page usually
> fairly accurate.

Yeah, that’s super unfortunate. You can find what’s _likely_ to be the dev in 
the © notice at the bottom of the game’s eShop page as well.


cheers,
Matija
-- 
gsm:	tel:+386.41.849.552
www:	https://matija.suklje.name
xmpp:	matija.suklje@gabbler.org
sip:	matija_suklje@ippi.fr

**Comment by Alshie** [comment]
Closing this - added dev field a while ago and have been using a mix of wikipedia & https://www.igdb.com/games/ to source. Thanks
