### ISSUE TITLE
Ikaruga!

### ISSUE THREAD

**Issue by snan** [Alshie/does-it-flip#34]
Help, my flip grip just arrived so I immediately hopped onto the eshop and bought Ikaruga and it doesn't work 💔 

The controls are also rotated so if I hit up in (when using the flip grip) I fly left and if I hit down I fly right.

HUD elements aren't rotated which is a secondary problem. The controls are the big issue.

I bought the flip grip for this game and bought this game for the flip grip. 😭

I have two games that do work ok (Switch&Shoot and The Walking Dead Pinball) but aaaah. I was all about that Ikaruga which I've never played but had on my bucket list

**Comment by snan** [comment]
Doomsday averted! There's a "change orientation" controller setting in system settings ♥

**Comment by snan** [comment]
Although you still might wanna change the database because I wouldn't say this works any better than something like Graceful Explosion Machine or Akane, I can play them about as well with the flip grip on as I can Ikaruga🤷🏻‍♀️

**Comment by snan** [comment]
Oh! Set rotate screen to left and set rotate hud to sync and then everything works perfectly with not even the rotate system setting control stick trick ♥

**Comment by Alshie** [comment]
Lol, sorry I was just coming to post this, I was sure it worked ok for me but had to wait until I could check on my switch.

I will update the instructions on site though to make this clear! Glad you got it sorted.
