### ISSUE TITLE
Moon Dancer (JP only, coming worldwide)

### ISSUE THREAD

**Issue by silverhook** [Alshie/does-it-flip#35]
Another shooter game from TERARIN (same guy as behind Missile Dancer) is out in the Japanese eShop, and is planned to release worldwide soon-ish:

https://store-jp.nintendo.com/list/software/70010000052954.html

It does support TATE.

**Comment by Alshie** [comment]
Thanks! Added now. Will update the how to instructions when I get a hold of it

**Comment by silverhook** [comment]
I have Moon Dancer, will give you the details shortly in a PR.
