### ISSUE TITLE
Add Pilgrims by Amanita Design

### ISSUE THREAD

**Issue by neildawson** [Alshie/does-it-flip#44]
[Pilgrims by Amanita Design](https://amanita-design.net/games/pilgrims.html) has a vertical mode, as demonstrated in this [example on Twitter](https://twitter.com/_mayatnikov/status/1608452448561111040).

**Comment by Alshie** [comment]
Thank you - have updated and added this :)

 https://www.doesitflip.com/games/pilgrims/
