### ISSUE TITLE
Murtop

### ISSUE THREAD

**Issue by hiulit** [Alshie/does-it-flip#54]
Murtop is a fast-paced arcade game packed with action, as if it was taken out directly from the 80's, where Dig Dug meets Bomberman https://games.hiulit.com/murtop/

It has a TATE option to rotate the screen in all directions :)

Link to the Nintendo's store: https://www.nintendo.com/us/store/products/murtop-switch/

**Comment by Alshie** [comment]
Added - thanks for letting me know - looks great!
